### ISSUE TITLE
Included LLVM is dated by a version 

### ISSUE THREAD

**Issue by ZackGC** [rhelmer/emscripten-vagrant#2]
Emscripten is using 3.1 now and the included version is 3.0. The bytecode format has changed and so some parts of emscripten are broken. I am downloading what I think is the correct version right now from this page: http://llvm.org/releases/download.html 
Should be a easy fix via a change in static assets or url.

**Comment by rhelmer** [comment]
Actually was up to 3.2 by now :)

**Comment by zmaril** [comment]
Woah! Awesome. Thank you.
