### ISSUE TITLE
VM appears not to run without cpu VT

### ISSUE THREAD

**Issue by rajsite** [rhelmer/emscripten-vagrant#3]
Hi rhelmer!

I tried running the vm with vagrant and was having problems connecting to the VM. I opened up VagrantFile and uncommented the gui configuration line to boot with a gui. Looks like virtualbox is giving a "VT-x/AMD-V hardware acceleration is not available on your system. Your 64-bit guest will fail to detect a 64-bit CPU and will not be able to boot."

Is the Ubuntu distro 64-bit? Is it possible to use a 32-bit Ubuntu for those with older cpus without VT or does a 64-bit Ubuntu provide any distinct advantage for use with emscripten?

**Comment by rhelmer** [comment]
@rajsite sure we can use 32-bit instead, I don't think there's any disadvantage right now.

**Comment by rhelmer** [comment]
Will be fixed by issue #5
